language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coveralls
- test ${TRAVIS_PULL_REQUEST} == "false" && test ${TRAVIS_BRANCH} == "master" && sh
  "$TRAVIS_BUILD_DIR/.travis-ci-bintray-credentials.sh" && sbt 'set version := version.value
  + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish
branches:
  only:
  - master
env:
  global:
  - secure: EZfdUxaBZwpqadShYAECB1DcfyABcJcuORNDhO6B9wYgB2rPCEr3DznzX01M1Pkmgi7C/OjtbyWyN8OcjQg+LbzfqFOo14WdJFvHlqNM/bnz5j90+P6eEWrer44Kw0/U3NVz4kG6vioNq8KHlzEEAgm+8mao4v64NkDwGWpWZp0=
  - secure: mfWpERfw6r5U2O9Tuok6QrlHV9a9sCsrBA0JDn9qCzaCRuZJaHI/e03+zH1dKpwS/rj6V1CUCt4vg4670Kyn27qSw6ZgAZWyrB0EQ+y1WbFFd7xJUExnKT7/ysM+P/qC0zqBEzT677PexPRBrhr/p4QbTSL2V/M6rLaz0E0cv1Q=
